name: Bandit

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit bandit-sarif-formatter

      - name: Run Bandit Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: .
          level: HIGH
          confidence: HIGH
          exit_zero: false

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
